# Generated by Django 5.1 on 2024-08-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Slider title')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Slider title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Slider title')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Slider title')),
                ('image', models.ImageField(upload_to='slider/', verbose_name='Slider image')),
                ('description', models.TextField(verbose_name='Slider description')),
                ('description_uz', models.TextField(null=True, verbose_name='Slider description')),
                ('description_en', models.TextField(null=True, verbose_name='Slider description')),
                ('description_ru', models.TextField(null=True, verbose_name='Slider description')),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Sliders',
            },
        ),
    ]
