# Generated by Django 5.1 on 2024-08-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('history_year', models.CharField(max_length=255, verbose_name='History year')),
                ('description', models.TextField(verbose_name='History description')),
                ('description_uz', models.TextField(null=True, verbose_name='History description')),
                ('description_en', models.TextField(null=True, verbose_name='History description')),
                ('description_ru', models.TextField(null=True, verbose_name='History description')),
                ('image', models.ImageField(upload_to='history/', verbose_name='History image')),
            ],
            options={
                'verbose_name': 'History',
                'verbose_name_plural': 'Histories',
            },
        ),
    ]
