# Generated by Django 5.1 on 2024-08-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_aboutcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Teacher')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='Teacher')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Teacher')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Teacher')),
                ('image', models.ImageField(upload_to='teacher/', verbose_name='Teacher image')),
                ('direction', models.CharField(max_length=255, verbose_name="Teacher's direction")),
                ('direction_uz', models.CharField(max_length=255, null=True, verbose_name="Teacher's direction")),
                ('direction_en', models.CharField(max_length=255, null=True, verbose_name="Teacher's direction")),
                ('direction_ru', models.CharField(max_length=255, null=True, verbose_name="Teacher's direction")),
                ('facebook_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Facebook link')),
                ('twitter_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Twitter link')),
                ('linkedin_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Linkedin link')),
                ('skype_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Skype link')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
            },
        ),
    ]
