# Generated by Django 5.1 on 2024-08-29 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Blog category name')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='Blog category name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Blog category name')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Blog category name')),
            ],
            options={
                'verbose_name': 'Blog category',
                'verbose_name_plural': 'Blog categories',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Blog title')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Blog title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Blog title')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Blog title')),
                ('slug', models.CharField(blank=True, max_length=255, null=True, verbose_name='Blog slug')),
                ('description', models.TextField(verbose_name='Blog description')),
                ('description_uz', models.TextField(null=True, verbose_name='Blog description')),
                ('description_en', models.TextField(null=True, verbose_name='Blog description')),
                ('description_ru', models.TextField(null=True, verbose_name='Blog description')),
                ('is_new', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.blogcategory', verbose_name='Blog category')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
    ]
