# Generated by Django 5.1 on 2024-08-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_blogcategory_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default=1, upload_to='blog/', verbose_name='Blog image'),
            preserve_default=False,
        ),
    ]
