# Generated by Django 5.1 on 2024-08-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_blog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Tag name')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='Tag name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Tag name')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Tag name')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
    ]
