# Generated by Django 5.1 on 2024-09-04 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Course name')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='Course name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Course name')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Course name')),
                ('description', models.TextField(verbose_name='Course description')),
                ('description_uz', models.TextField(null=True, verbose_name='Course description')),
                ('description_en', models.TextField(null=True, verbose_name='Course description')),
                ('description_ru', models.TextField(null=True, verbose_name='Course description')),
                ('image', models.ImageField(upload_to='course/', verbose_name='Course image')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
    ]
