# Generated by Django 5.1 on 2024-11-22 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Partner',
        ),
    ]
